# Generated by Django 3.2.5 on 2021-07-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Contact',
        ),
    ]
